Add standard input/output page
km45/cpp-book pull request #12
Opened 2019-05-16 02:54 UTC by cpmrph

2019-05-18 18:10 UTC, km45 requested changes

2019-05-18 18:10 UTC, km45 commented on docs/ch05-01-standard-inout.md
> +{
既存箇所のサンプルコードにあわせて `int main() {` と1行にまとめるようお願いします。

2019-05-24 07:34 UTC, cpmrph commented on docs/ch05-01-standard-inout.md
> +{
ありがとうございます。 87cc878 でフォーマットしました。

2019-05-25 14:37 UTC, km45 approved these changes

2019-05-30 07:28 UTC, merged