Add memory management chapter
km45/cpp-book pull request #13
Opened 2019-05-24 07:33 UTC by cpmrph

2019-05-25 14:36 UTC, km45 requested changes

2019-05-25 14:36 UTC, km45 commented on docs/ch06-02-new-and-delete.md
> +    } // int[100000] 分のメモリが開放されないままになる。
main 関数をプログラム中から呼び出さない限り、
main 関数の終了はプログラムの終了と同様に解釈されると思います。

一般に、
解放漏れ領域はプログラム終了時に OS が後処理として解放するので、
こうした議論が発生しないように main 関数ではない関数にした方がいいと思います。

2019-05-25 14:36 UTC, km45 commented on docs/ch06-05-smart-pointers.md
> +    std::cout << *x << std::endl;
main 関数では `return 0;` は省略可能ですが、他の箇所にあわせて明記をお願いします。

2019-05-28 12:12 UTC, cpmrph commented on docs/ch06-05-smart-pointers.md
> +    std::cout << *x << std::endl;
b69c3aa にてreturn文を追加しました。

2019-05-28 12:15 UTC, cpmrph commented on docs/ch06-02-new-and-delete.md
> +    } // int[100000] 分のメモリが開放されないままになる。
なるほど、確かにmain関数ではサンプルコードの意図がぶれてしまいますね…。
03fece9 にて `void Function()` に変更しました。

2019-05-28 18:05 UTC, km45 approved these changes

2019-05-30 07:54 UTC, merged