Add error handling chapter
km45/cpp-book pull request #14
Opened 2019-06-01 08:44 UTC by km45

2019-06-03 09:32 UTC, cpmrph requested changes

2019-06-03 09:32 UTC, cpmrph commented on docs/ch10-01-exceptions.md
> +[Google C++ Style Guide]: https://google.github.io/styleguide/cppguide.html#Exceptions]
![badge](https://img.shields.io/badge/review-must-red.svg)
リンク末尾の`]`が不要です。

2019-06-03 09:32 UTC, cpmrph commented on docs/ch10-01-exceptions.md
> +int StringToInt(const std::string& str) noexcept(noexcept(CharToInt('0')));
![badge](https://img.shields.io/badge/review-imo-ff69b4.svg)
`CharToInt('0')`が`'0'`決め打ちなのが気になりました。
`CharToInt(char())`でも良いのかなと。

2019-06-03 09:32 UTC, cpmrph commented on docs/ch10-01-exceptions.md
> +標準ライブラリで `std::logic_error` を送出するものはありません。
![badge](https://img.shields.io/badge/review-imo-ff69b4.svg)
個人的には`std::logic_error`の直後に、
継承先クラスである`std::invalid_argument` `std::out_of_range`の説明があった方が読みやすいと感じました。
人によって意見が分かれそうなところなので、見直してみて違和感がなければ今のままでも良いです。

2019-06-03 09:32 UTC, cpmrph commented on docs/ch10-01-exceptions.md
> +    // デストラクタは暗黙的に noexcept になるため noexcept(falsee) を明示的に指定
![badge](https://img.shields.io/badge/review-must-red.svg)
`falsee` -> `false`

2019-06-03 09:32 UTC, cpmrph commented on docs/ch10-01-exceptions.md
> +[std::terminate][cpprefjp_terminate] が呼び出されてプログラムが異常終了します。
![badge](https://img.shields.io/badge/review-must-red.svg)
読み解きにくい一文になっているため、見直しをお願いします。

前半部を消して
```
「例外を送出して捕捉するまでの間に、さらにデストラクタから例外を送出する」ことになってしまい、std::terminateが呼び出されてプログラムが異常終了します。
```
とかでも良いかもしれません。

2019-06-04 05:08 UTC, km45 commented on docs/ch10-01-exceptions.md
> +[Google C++ Style Guide]: https://google.github.io/styleguide/cppguide.html#Exceptions]
fbe4bcf で修正しました。

2019-06-04 05:10 UTC, km45 commented on docs/ch10-01-exceptions.md
> +    // デストラクタは暗黙的に noexcept になるため noexcept(falsee) を明示的に指定
58a5289df で修正しました。

2019-06-04 05:13 UTC, km45 commented on docs/ch10-01-exceptions.md
> +[std::terminate][cpprefjp_terminate] が呼び出されてプログラムが異常終了します。
bc866d2 にて修正しました。
修正にあたっては、提示いただいた文をそのまま採用させていただきました。

2019-06-04 05:19 UTC, km45 commented on docs/ch10-01-exceptions.md
> +int StringToInt(const std::string& str) noexcept(noexcept(CharToInt('0')));
私も気になっていたのですが、確かに `char()` で代用できますね。
0f7a417 にて修正しました。

2019-06-04 05:25 UTC, km45 commented on docs/ch10-01-exceptions.md
> +標準ライブラリで `std::logic_error` を送出するものはありません。
3638070 にて順番を変更しました。

クラス図に対して幅優先か深さ優先で迷っていたもので、
例が非常に多い想定で幅優先にしたのですが PR を出す時点では例を絞ったため
深さ優先の方が確かに分かりやすいと思い提案いただいた順番に変更しました。

2019-06-04 05:48 UTC, cpmrph approved these changes

2019-06-04 16:00 UTC, merged