Add malloc & free page
km45/cpp-book pull request #21
Opened 2019-06-06 01:20 UTC by cpmrph

2019-06-08 06:03 UTC, km45 requested changes

2019-06-08 06:03 UTC, km45 commented on docs/ch06-02-new-and-delete.md
> +!!! Tips "malloc/free"
`Tips` という admonition はなく、デフォルトの `info` として出力されています。
https://squidfunk.github.io/mkdocs-material/extensions/admonition/

`tip` のことかなと推測しましたが、内容からすると `warning` などが妥当だと思います。

2019-06-10 03:13 UTC, cpmrph commented on docs/ch06-02-new-and-delete.md
> +!!! Tips "malloc/free"
2fb65df にて `warning` に変えました。
合わせて、Admonitionのドキュメントのように小文字でキーワードを記載するように全体的に見直しました。

2019-06-10 17:44 UTC, km45 approved these changes

2019-06-12 04:11 UTC, merged