Add gtest page
km45/cpp-book pull request #25
Opened 2019-06-06 01:24 UTC by cpmrph

2019-06-08 07:01 UTC, km45 requested changes

2019-06-08 07:01 UTC, km45 commented on docs/test-how-to-gtest.md
> +int IsEven(int x) {
ヘッダファイルでの宣言は戻り値が `bool` ですが、
ソースコードでの定義は戻り値が `int` で一致していません。

意図したものではないと思いますので修正をお願いします。

2019-06-08 07:01 UTC, km45 commented on docs/test-how-to-gtest.md
> +
テストケース名とテスト名には `_` を含んではいけないことを記載しておいた方がいいと思います。
http://opencv.jp/googletestdocs/primer.html#primer-simple-tests

`gtest` の内部でこの2つを `_` で連結してシンボル名を生成するような処理をしており、
`_` を許可すると `TEST(A_B, C)` と `TEST(A, B_C)` がともに `A_B_C` のように展開されて
シンボル衝突が発生することがありうるからという理由だったはずです。
(この理由は記載する必要はないと思います。)

2019-06-08 07:01 UTC, km45 commented on docs/test-how-to-gtest.md
> +EXPECT_GE(val1, val2);  // val1 <= val2 か
LT や GT の説明が逆になっています。
http://opencv.jp/googletestdocs/primer.html#primer-binary-comparison

たとえば `EXPECT_LT` は `val1 > val2 か` ではなく `val1 < val2 か` の検証です。

修正をお願いします。

2019-06-08 08:06 UTC, km45 requested changes

2019-06-08 08:06 UTC, km45 commented on docs/test-how-to-gtest.md
> +#include "sample.h"
インクルードの追加をお願いします。

2019-06-10 03:01 UTC, cpmrph commented on docs/test-how-to-gtest.md
> +int IsEven(int x) {
6083503 にて対応しました。

2019-06-10 03:02 UTC, cpmrph commented on docs/test-how-to-gtest.md
> +EXPECT_GE(val1, val2);  // val1 <= val2 か
36c0747 にて対応しました。

2019-06-10 03:02 UTC, cpmrph commented on docs/test-how-to-gtest.md
> +#include "sample.h"
b3eb67b にて対応しました

2019-06-10 03:02 UTC, cpmrph commented on docs/test-how-to-gtest.md
> +
b3eb67b にて対応しました

2019-06-10 03:03 UTC, cpmrph commented on docs/test-how-to-gtest.md
> +#include "sample.h"
指摘の意図が汲み取れませんでした。。。
何のインクルードが必要でしょうか？

2019-06-10 17:41 UTC, km45 commented on docs/test-how-to-gtest.md
> +#include "sample.h"
すみません。おそらく私のコメントのミスです。
無視していただいて問題ありません。

2019-06-10 17:42 UTC, km45 approved these changes

2019-06-12 04:00 UTC, merged