Add debug pages
km45/cpp-book pull request #27
Opened 2019-06-09 14:07 UTC by km45

2019-06-10 10:08 UTC, cpmrph requested changes

2019-06-10 10:08 UTC, cpmrph commented on docs/debug-gdb.md
> +```gdb
![badge](https://img.shields.io/badge/review-imo-ff69b4.svg)
`gdb` のシンタックスハイライトは用意されていなさそうなので、 `gdb` の記載はなくても良いかなと思いました。

2019-06-10 10:08 UTC, cpmrph commented on docs/debug-gdb.md
> +```cpp
![badge](https://img.shields.io/badge/review-must-red.svg)
内容がC++ではないですが `cpp` になっています

2019-06-11 10:51 UTC, km45 commented on docs/debug-gdb.md
> +```cpp
ab4bfa3 で修正しました。

2019-06-11 11:04 UTC, km45 commented on docs/debug-gdb.md
> +```gdb
75a9957 で修正しました。

https://github.com/github/linguist/blob/master/lib/linguist/languages.yml
を見て gdb という指定をしたのですが、
https://squidfunk.github.io/mkdocs-material/extensions/codehilite/#supported-languages-excerpt
で Pygments を使用していると記載してあり、
http://pygments.org/languages/
を確認したところ gdb という指定は無効なことを確認したので削除しました。

2019-06-11 13:08 UTC, cpmrph approved these changes

2019-06-11 13:57 UTC, merged