Add function objects page
km45/cpp-book pull request #37
Opened 2019-06-14 12:12 UTC by cpmrph

2019-06-14 16:41 UTC, km45 requested changes

2019-06-14 16:41 UTC, km45 commented on docs/ch02-09-function-objects.md
> +| [=, &a] | 変数 `a` は参照し、それ以外はコピーしてラムダ式の中で使う      |
記述例の方もインラインコードとして扱った方がいいと思います。

2019-06-14 16:41 UTC, km45 commented on docs/ch02-09-function-objects.md
> +    std::cout << g(4, 7) << std::endl;       // 28
未定義の `g` が使用されているので修正をお願いします。

2019-06-15 07:43 UTC, cpmrph commented on docs/ch02-09-function-objects.md
> +| [=, &a] | 変数 `a` は参照し、それ以外はコピーしてラムダ式の中で使う      |
5469ef1 にて修正しました。

2019-06-15 07:44 UTC, cpmrph commented on docs/ch02-09-function-objects.md
> +    std::cout << g(4, 7) << std::endl;       // 28
91d488a にて修正しました。

2019-06-15 09:23 UTC, km45 approved these changes

2019-06-17 02:18 UTC, merged