Explain make and Makefile
km45/cpp-book pull request #44
Opened 2019-06-15 14:14 UTC by km45

2019-06-17 03:02 UTC, cpmrph requested changes

2019-06-17 03:02 UTC, cpmrph commented on docs/make-make.md
> +`main.cc` をビルドして `a.exe` を生成する場合は `Makefile` を次のようにします。
![badge](https://img.shields.io/badge/review-must-red.svg) ![badge](https://img.shields.io/badge/review-imo-ff69b4.svg)
`make` について明るくない人が読むと、
- `Makefile` が突然出てきた
- 既にPC内のどこかに存在する `Makefile` というものを修正する

といった印象を受けるように思いました。

- `make` が `Makefile` で動くこと
- `Makefile` を新規で作成する必要があること

が伝わるような文にしたいです。

##### 案
```
make は Makefile を読み込んで動作します。
main.cc をビルドして a.exe を生成する場合は、 Makefile を作成し、次のように記述します。
```

2019-06-17 16:18 UTC, km45 commented on docs/make-make.md
> +`main.cc` をビルドして `a.exe` を生成する場合は `Makefile` を次のようにします。
提示いただいた案と hello-world の箇所の文章を参考にしながら修正しました。
cfdf2e2

こちらでいかがでしょうか。

2019-06-18 09:16 UTC, cpmrph approved these changes

2019-06-18 15:55 UTC, merged