Explain cmake
km45/cpp-book pull request #49
Opened 2019-06-16 13:39 UTC by km45

`mkdocs.yml` の関係で #44 を含んでいます。

この PR での変更は bcbe0f1 だけです。

2019-06-17 03:14 UTC, cpmrph requested changes

2019-06-17 03:14 UTC, cpmrph commented on docs/make-cmake.md
> +`main.cc` をビルドして `a.exe` を生成する場合は `CMakeLists.txt` を次のようにします。
![badge](https://img.shields.io/badge/review-must-red.svg) ![badge](https://img.shields.io/badge/review-imo-ff69b4.svg)
`Makefile` に関する指摘 https://github.com/km45/cpp-book/pull/44#discussion_r294122966 と同様に、こちらも表現を変えて頂きたいです。

2019-06-18 17:42 UTC, km45 commented on docs/make-cmake.md
> +`main.cc` をビルドして `a.exe` を生成する場合は `CMakeLists.txt` を次のようにします。
修正しました。
96079f8

2019-06-19 17:26 UTC, km45 commented
https://github.com/rinatz/cpp-book/pull/8
へ移動したためこちらはクローズします

2019-06-19 17:26 UTC, closed without merging