Add multiple files page
km45/cpp-book pull request #5
Opened 2019-05-10 06:53 UTC by cpmrph

2019-05-10 16:29 UTC, km45 requested changes

2019-05-10 16:29 UTC, km45 commented on docs/ch04-01-multiple-files.md
> +`A_H_` の部分は他のヘッダと名前が被らなければどのような命名でも構いません。
> どのような命名でも構いません

`予約済み識別子` は使用してはいけないため修正をお願いします。

2019-05-13 01:56 UTC, cpmrph commented on docs/ch04-01-multiple-files.md
> +`A_H_` の部分は他のヘッダと名前が被らなければどのような命名でも構いません。
@km45 
c265eb46215bfc818623bb818fd6512f787a0b76 で `予約済み識別子` との重複について記載しました。

2019-05-13 04:17 UTC, km45 approved these changes

2019-05-15 00:52 UTC, merged