Add scopes page
km45/cpp-book pull request #51
Opened 2019-06-17 13:20 UTC by cpmrph

2019-06-17 15:48 UTC, km45 requested changes

2019-06-17 15:48 UTC, km45 commented on docs/ch04-02-scopes.md
> +int x = 100;  // グローバル変数
ヘッダファイルでこのように変数定義を行うと、
2つ以上のソースファイルからインクルードされた場合に多重定義となると思います。

C++17 で追加された `inline` 変数ではこの問題が解消できる認識です (齟齬があったらすみません) が、
C++11 では `extern` 宣言が必要だと思います。

2019-06-17 15:48 UTC, km45 commented on docs/ch04-02-scopes.md
> +同一の名前空間内に指定したシンボルが見つからなかった場合、シンボルを探す範囲を `namespace` ブロック毎に外に広げていき、最初に見つかったものが利用されます。
> シンボルを探す範囲を `namespace` ブロック毎に外に広げていき、最初に見つかったものが利用されます

こちらについて自信がないのですが、根拠 (出典など) はあるでしょうか？

2019-06-17 15:48 UTC, km45 commented on docs/ch04-02-scopes.md
> +
どこで記載するべきかは悩ましいのですが、
ADL についてもリンクだけはあった方がいい気がします。

参考:
https://ja.cppreference.com/w/cpp/language/adl
http://cpp.aquariuscode.com/argument-dependent-lookup

2019-06-17 16:20 UTC, km45 commented on docs/ch04-02-scopes.md
> +
ただ、かなり難しい話なのであえて記載しないという判断はありかもしれません。

2019-06-18 02:37 UTC, cpmrph commented on docs/ch04-02-scopes.md
> +同一の名前空間内に指定したシンボルが見つからなかった場合、シンボルを探す範囲を `namespace` ブロック毎に外に広げていき、最初に見つかったものが利用されます。
下記ページの「名前空間スコープ」のイメージで書きました。
https://ja.cppreference.com/w/cpp/language/unqualified_lookup

2019-06-18 09:40 UTC, cpmrph commented on docs/ch04-02-scopes.md
> +int x = 100;  // グローバル変数
確かにその通りですね。。。
ファイルを分けなくてもグローバル変数については説明可能なので、サンプルコードを1ファイルに纏めました。 38a7fb7

`extern` については説明するべきか別途検討しますが、
説明する場合は `static` と合わせて別ページになるかなと思っています。

2019-06-18 09:48 UTC, cpmrph commented on docs/ch04-02-scopes.md
> +
>かなり難しい話なのであえて記載しないという判断はありかもしれません。
個人的には、これと同意見でここに記載する必要はないと思っています。
書くとしたら付録側の方でも良い気がします。

2019-06-18 15:04 UTC, km45 commented on docs/ch04-02-scopes.md
> +
もし付録で対応するとしても、別ブランチでの対応になると思います。
このブランチ (PR) では対応しないという判断でいいと思います。

2019-06-19 07:13 UTC, cpmrph commented
5章の構成含めて見直しをかけるので、本PRはクローズします。

2019-06-19 07:13 UTC, closed without merging